import { useState } from 'react';
import { Link, useLocation } from '@tanstack/react-router';
import { ArrowLeft, ArrowUpRight, Bot, FileText, Play } from 'lucide-react';
import './exam-slice.css';
import './exam-slice-v2-fixes.css';
import './exam-slice-v2-1.css';

const subjects = [['数据结构', 'DS'], ['计算机组成原理', 'CO'], ['操作系统', 'OS'], ['计算机网络', 'CN']] as const;
const nodes = [['MM-01', '存储管理基础', '逻辑地址与物理地址'], ['MM-02', '虚拟内存地址映射', '页号、页表与物理帧'], ['MM-03', '页面置换算法', '缺页处理与置换策略'], ['MM-04', '工作集与抖动', '局部性与内存分配']] as const;
const A = ({ children }: { children: React.ReactNode }) => <Link className="exam-action" to="/exam/11408/operating-system/workspace">{children}<ArrowUpRight aria-hidden="true" /></Link>;
const Crumb = ({ current, back }: { current: string; back: string }) => <div className="exam-crumb"><Link to={back as '/exam' | '/exam/11408'}><ArrowLeft aria-hidden="true" />返回</Link><span>考研 / 11408 / {current}</span></div>;

function Note({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <aside className={`journal-note ${className}`}>{children}</aside>; }
function MemoryDiagram() { return <figure className="memory-diagram" aria-label="虚拟地址经页表映射到物理帧"><div><b>VIRTUAL ADDRESS</b><strong>PAGE 02</strong><span>OFFSET 0x3F</span></div><i /><div className="is-table"><b>PAGE TABLE</b><strong>ROW 02</strong><span>FRAME 05</span></div><i /><div className="is-frame"><b>PHYSICAL FRAME</b><strong>05</strong><span>OFFSET 0x3F</span></div><figcaption>虚拟地址 <em>→</em> 页表 <em>→</em> 物理帧</figcaption></figure>; }
function SubjectRoute() { return <div className="subject-route" aria-label="11408 四科备考路线">{subjects.map(([name, code], index) => <Link key={code} to={code === 'OS' ? '/exam/11408/operating-system' : '/exam/11408'} className={code === 'OS' ? 'is-current' : ''}><b>{String(index + 1).padStart(2, '0')}</b><strong>{code}</strong><span>{name}</span>{index < 3 && <i aria-hidden="true" />}</Link>)}</div>; }
function TargetMap() { return <div className="target-map" aria-label="11408 考试目标图"><div><small>TARGET</small><strong>计算机考研</strong></div><i /><div><small>EXAM CODE</small><strong>11408</strong><span>当前开放目标</span></div><ol>{subjects.map(([name, code]) => <li className={code === 'OS' ? 'is-current' : ''} key={code}><b>{code}</b>{name}</li>)}</ol><p>OS 是当前学习焦点，不代表个人进度。</p></div>; }

export function ExamWorldPage() { const pathname = useLocation({ select: l => l.pathname }); if (pathname.endsWith('/workspace')) return <LearningWorkspacePage />; if (pathname.endsWith('/operating-system')) return <OperatingSystemPage />; if (pathname.endsWith('/11408')) return <Exam11408Page />; return <main className="exam-page exam-world"><section className="world-intro"><div><p>考研学习 / TARGET MAP</p><h1>把准备，放回<br />一个明确的目标里。</h1><article>选择考试目标，然后沿着阶段、科目与知识结构继续推进。当前开放的完整目标是计算机考研 11408。</article><Link className="exam-action" to="/exam/11408">进入 11408<ArrowUpRight aria-hidden="true" /></Link></div><TargetMap /></section><Note className="world-note">目标不是待办清单。<br />它是一条可回看的学习坐标。</Note><footer>数学、英语、联考等方向保留为后续扩展架构；当前不展示未实现的学习数据或入口。</footer></main>; }
export function Exam11408Page() { return <main className="exam-page study-route-page"><Crumb current="11408" back="/exam" /><section className="journal-hero"><div><p>2027 计算机考研 / STUDY ROUTE</p><h1>11408 的<br />备考地图</h1><article>从四门基础课出发，把当前节点、下一行动与完整路径放在同一张目标图里。</article></div><div className="route-sheet"><b>11408 / FOUR SUBJECTS</b><SubjectRoute /><Note>沿目标轴进入学习，<br />而不是把四科拆成四张卡片。</Note></div></section><section className="focus-panel"><div><p>当前学习焦点</p><h2>操作系统<br /><span>存储管理</span></h2><article>当前焦点是结构位置，不是完成百分比或个人掌握度。</article></div><div><small>FOCUS</small><strong>OS</strong><Link to="/exam/11408/operating-system">查看知识结构 <ArrowUpRight /></Link></div></section><section className="exam-next"><div><p>下一结构节点</p><h2>页面置换算法</h2><article>这是虚拟内存地址映射完成后的结构性下一步，并非 AI 推荐。</article></div><A>继续学习</A></section></main>; }
export function OperatingSystemPage() { return <main className="exam-page os-page"><Crumb current="操作系统" back="/exam/11408" /><section className="os-hero"><div><p>11408 / 操作系统 / KNOWLEDGE MAP</p><h1>从备考目标，进入<br />知识的组织方式。</h1><article>当前聚焦存储管理。这里展示知识结构和可进入的学习行动，而不是课程式目录。</article><Note>先理解地址映射，<br />再处理页面置换。</Note></div><MemoryDiagram /><div className="os-current"><small>当前节点</small><strong>虚拟内存地址映射</strong><span>页号、页表与物理帧</span><A>继续学习</A></div></section><section className="os-map"><div><p>存储管理 / MEMORY MANAGEMENT</p><h2>从地址到<br />物理帧</h2><article>沿节点推进：先理解地址映射，再处理页面置换。</article></div><ol className="knowledge-path">{nodes.map(([id, name, note], index) => <li className={index === 1 ? 'is-current' : ''} key={id}><span /><b>{id}</b><div><h3>{name}</h3><p>{note}</p></div>{index === 1 ? <><small>当前学习节点</small><A>开始当前节点</A></> : <small>{index === 0 ? '建立概念基础' : index === 2 ? '处理缺页异常' : '进入性能视角'}</small>}</li>)}</ol><Note className="map-note">理解映射的本质，<br />才能真正掌握虚拟内存。</Note></section><footer>章节练习与个人学习状态将在真实 API 可用时读取；未以示例进度、掌握度或题目数量替代。</footer></main>; }
export function LearningWorkspacePage() { const [tool, setTool] = useState<'none' | 'ai' | 'resource' | 'relation' | 'hint'>('none'); const title = tool === 'ai' ? 'AI Tutor' : tool === 'resource' ? '相关资料' : tool === 'relation' ? '关联关系' : '提示'; const text = tool === 'ai' ? '提问会自动携带：11408 · 操作系统 · 存储管理 · 虚拟内存。' : tool === 'relation' ? '页表连接虚拟页号与物理帧号；页内偏移在映射两端保持同一位置。' : '页表把虚页号换成物理帧号；页内偏移描述页内位置，所以它无需改变。'; return <main className="exam-page workspace"><Crumb current="虚拟内存地址映射" back="/exam/11408/operating-system" /><header><p>11408 · 操作系统 · 存储管理 / LEARNING JOURNAL</p><h1>一个虚拟地址，是怎样找到物理内存中的位置的？</h1><span>当前学习对象：虚拟内存地址映射</span></header><section className="workspace-journal"><div><nav className="steps"><b>01 理解</b><span>02 映射</span><span>03 结果</span><span>04 检查</span></nav><article className="lede">程序看到的是虚拟地址；硬件与操作系统通过页表，把其中的页号定位到一个物理帧，再保留页内偏移完成转换。</article><div className="mapping-sheet"><div><p>VISUAL EXPLANATION</p><h2>地址翻译的<br />三个保留与替换</h2><Note>页号会被替换，<br />页内偏移不会改变。</Note></div><MemoryDiagram /><ol><li><b>01</b>保留页内偏移</li><li><b>02</b>页表查找物理帧</li><li><b>03</b>组合成物理地址</li></ol></div><div className="check"><div><p>轻量检查 / CHECK</p><h2>页内偏移在映射后为什么不变？</h2></div><button onClick={() => setTool('hint')}>查看提示</button></div></div><aside className="tool-rail"><p>CONTEXT TOOLS</p><button onClick={() => setTool(tool === 'ai' ? 'none' : 'ai')}><Bot />问 AI</button><button onClick={() => setTool(tool === 'resource' ? 'none' : 'resource')}><FileText />相关资料</button><button onClick={() => setTool(tool === 'relation' ? 'none' : 'relation')}>↗ 关联关系</button>{tool !== 'none' && <div className="tool"><strong>{title}</strong><p>{text}</p></div>}</aside></section><section className="exam-next"><div><p>完成后 / NEXT</p><h2>继续到页面置换算法</h2><article>这是存储管理路径中的下一个结构节点，不是个人化或 AI 推荐。</article></div><Link className="exam-action" to="/exam/11408/operating-system">回到知识结构 <ArrowUpRight /></Link></section><footer><Play />练习入口将使用现有章节题目接口；当前原型不伪造统一题库。</footer></main>; }
