import { useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import type { components } from "@/types/api";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useExamCatalog } from "@/features/exam/api/catalog";
import { ApiRequestError, useExamSubjectContentStatus } from "@/features/exam/api/content-status";
import { useExamProfile, useSaveExamProfile } from "@/features/exam/api/profile";
import { normalizeApiError } from "@/features/exam/api/errors";
import { resolveReturnDestination } from "@/features/auth/return-to";
import { isKnownExamSubject, profileAction } from "@/features/exam/view-models/profile";
import { ContentUnavailableState } from "./content-unavailable-state";
import { ExamPageShell } from "./exam-page-shell";
import { SubjectAvailabilityBadge } from "./subject-availability-badge";
import { ConfigurationStepRail, DossierHeader, IndexRow } from "./exam-visual-primitives";

type Catalog = components["schemas"]["ExamPrepCatalogResponse"];
type Profile = components["schemas"]["ExamPrepProfileResponse"];
type Subject = components["schemas"]["ExamSubjectSummary"];
const categoryLabels: Record<string, string> = { public: "公共课", professional: "专业统考" };
const indexOf = (value: number) => String(value).padStart(2, "0");
const categories = (catalog: Catalog) => [...new Set(catalog.subjects.map((subject) => subject.category))];
const categoryLabel = (category: string) => categoryLabels[category] ?? category;

function LoadingRows() { return <div className="space-y-5"><Skeleton className="h-10 w-48" /><Skeleton className="h-48 w-full" /><Skeleton className="h-20 w-full" /></div>; }
function apiState(error: unknown) { return error instanceof ApiRequestError ? normalizeApiError(error.status, error.detail) : normalizeApiError(undefined); }
function RequestState({ error }: { error: unknown }) { const state = apiState(error); return <section className="max-w-reading border-y border-lab-grid/45 py-12"><h1 className="text-page-title font-bold">{state.kind === "authentication_required" ? "需要登录" : "暂时无法加载"}</h1><p className="mt-4 text-body text-text-secondary">{state.message}</p></section>; }

function SubjectIndexRow({ subject, selected, index }: { subject: Subject; selected?: boolean; index: number }) {
  const active = subject.availability === "active";
  const detail = active ? subject.modules.map((module) => module.display_name).join(" / ") || subject.description : selected ? "已加入我的备考，学习内容将后续开放。" : "可加入我的备考，学习内容将后续开放。";
  const action = active ? <Button asChild><Link to="/exam/cs408">进入学习<ArrowRight className="size-4" aria-hidden="true" /></Link></Button> : <Button asChild variant="ghost"><Link to="/exam/subjects/$subjectId" params={{ subjectId: subject.id }}>{selected ? "查看状态" : "加入备考"}<ArrowRight className="size-4" aria-hidden="true" /></Link></Button>;
  return <IndexRow index={indexOf(index)} title={subject.display_name} meta={detail} status={<SubjectAvailabilityBadge availability={subject.availability} />} action={action} active={active} />;
}

function SubjectGroup({ title, subjects, selected, startIndex = 1 }: { title: string; subjects: Subject[]; selected?: boolean; startIndex?: number }) {
  return <section className="exam-section"><div className="exam-section__heading"><p>{title}</p><h2>{selected ? "学习路径" : "科目索引"}</h2></div><ul className="exam-index-list">{subjects.map((subject, index) => <SubjectIndexRow key={subject.id} subject={subject} selected={selected} index={startIndex + index} />)}</ul></section>;
}

function MyExamConfigured({ catalog, profile }: { catalog: Catalog; profile: Profile }) {
  const knownSubjects = profile.subjects.filter(isKnownExamSubject);
  const activeSubjects = knownSubjects.filter((subject) => subject.availability === "active");
  const frameworkSubjects = knownSubjects.filter((subject) => subject.availability === "framework_only");
  const track = catalog.tracks.find((item) => item.id === profile.selected_track);
  const action = profileAction(profile);
  return <><DossierHeader index="01" eyebrow="备考档案" title="全国统考研究生考试" dark><div className="exam-dossier__meta">{profile.target_exam_year ? <span>目标考试年份 · {profile.target_exam_year}</span> : null}{track ? <span>备考方向 · {track.display_name}</span> : null}</div><div className="exam-dossier__action"><Button asChild><Link to={action === "进入 CS408" ? "/exam/cs408" : "/exam/setup"}>{action}<ArrowRight className="size-4" /></Link></Button></div></DossierHeader><section className="exam-section" aria-labelledby="my-subjects"><div className="exam-section__heading"><p>02 科目范围</p><h2 id="my-subjects">我的科目</h2></div>{activeSubjects.length ? <SubjectGroup title="可开始学习" subjects={activeSubjects} selected /> : null}{frameworkSubjects.length ? <SubjectGroup title="内容建设中" subjects={frameworkSubjects} selected startIndex={activeSubjects.length + 1} /> : null}{profile.subjects.filter((subject) => !isKnownExamSubject(subject)).map((subject) => <div key={subject.id} className="mt-6 border-y border-warning/30 bg-warning-soft p-5"><p className="font-semibold">未知/已下线科目</p><p className="mt-2 text-metadata text-text-secondary">{subject.id}</p><Button asChild variant="ghost" className="mt-3"><Link to="/exam/setup">编辑备考设置</Link></Button></div>)}{profile.subjects.length === 0 ? <p className="mt-6 border-y border-lab-grid/45 py-6 text-body text-text-secondary">尚未选择科目。请在备考设置中确认你的科目范围。</p> : null}</section></>;
}

export function MyExamPage() { const profile = useExamProfile(); const catalog = useExamCatalog(); if (profile.isPending || catalog.isPending) return <ExamPageShell activeItem="overview"><LoadingRows /></ExamPageShell>; if (profile.isError || catalog.isError) return <ExamPageShell activeItem="overview"><RequestState error={profile.error ?? catalog.error} /></ExamPageShell>; if (!profile.data.configured) return <ExamPageShell activeItem="overview"><DossierHeader index="01" eyebrow="备考档案" title="开始设置你的备考范围"><p className="exam-dossier__meta">选择备考方向、实际考试科目和目标年份。你的科目选择由你确认，不由方向模板替你决定。</p><div className="exam-dossier__action"><Button asChild><Link to="/exam/setup">设置我的备考<ArrowRight className="size-4" /></Link></Button></div></DossierHeader></ExamPageShell>; return <ExamPageShell activeItem="overview"><MyExamConfigured catalog={catalog.data} profile={profile.data} /></ExamPageShell>; }

function SelectionRow({ children }: { children: ReactNode }) { return <label className="exam-selection-row">{children}</label>; }
function SetupForm({ catalog, profile, destination }: { catalog: Catalog; profile: Profile; destination: string }) {
  const navigate = useNavigate(); const save = useSaveExamProfile(); const [track, setTrack] = useState(profile.selected_track ?? ""); const [subjects, setSubjects] = useState(profile.selected_subjects); const [year, setYear] = useState(profile.target_exam_year?.toString() ?? "");
  const toggleSubject = (id: string) => setSubjects((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  // Saving the profile is what makes the exam space configured; the save hook writes the server's
  // own payload back into the cache, so the space context is re-read without a second request.
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await save.mutateAsync({ selected_track: track || null, selected_subjects: subjects, target_exam_year: year ? Number(year) : null }); await navigate({ href: destination }); };
  const selectedTrack = catalog.tracks.find((item) => item.id === track)?.display_name ?? "未选择";
  return <form onSubmit={submit} className="exam-configuration"><fieldset className="border-y border-lab-grid/45 py-8"><legend>备考方向</legend><p className="mt-3 text-body text-text-secondary">确定考试方向；它不会自动改写你的实际科目。</p><div className="mt-5">{catalog.tracks.map((item) => <SelectionRow key={item.id}><input type="radio" name="track" value={item.id} checked={track === item.id} onChange={() => setTrack(item.id)} /><span><strong>{item.display_name}</strong><small>{item.description}</small></span></SelectionRow>)}</div></fieldset><fieldset className="border-b border-lab-grid/45 py-8"><legend>实际备考科目</legend><p className="mt-3 text-body text-text-secondary">科目由你确认；调整方向不会自动改写已选科目。</p>{categories(catalog).map((category) => <div key={category} className="mt-7"><h2>{categoryLabel(category)}</h2><div className="mt-3">{catalog.subjects.filter((subject) => subject.category === category).map((subject) => <SelectionRow key={subject.id}><input type="checkbox" checked={subjects.includes(subject.id)} onChange={() => toggleSubject(subject.id)} /><span><strong>{subject.display_name}</strong></span><SubjectAvailabilityBadge availability={subject.availability} /></SelectionRow>)}</div></div>)}</fieldset><div className="border-b border-lab-grid/45 py-8"><label className="block text-card-title font-semibold" htmlFor="target-year">目标考试年份</label><input id="target-year" className="mt-4 h-11 w-full max-w-56 border border-border-default bg-surface px-3" type="number" inputMode="numeric" value={year} onChange={(event) => setYear(event.target.value)} /><p className="mt-2 text-metadata text-text-secondary">此年份是你的目标，不是真题年份。</p></div>{save.isError ? <p role="alert" className="mt-5 text-danger-ink">{apiState(save.error).kind === "authentication_required" ? "需要登录后才能保存备考设置。" : "保存失败，请检查填写内容后重试。"}</p> : null}<aside className="exam-review" aria-label="备考设置确认"><p className="exam-kicker">04 确认</p><div className="exam-review__values"><span>方向 · <strong>{selectedTrack}</strong></span><span>科目 · <strong>{subjects.length ? subjects.join(" / ") : "未选择"}</strong></span><span>目标年份 · <strong>{year || "未填写"}</strong></span></div><Button type="submit" disabled={save.isPending} className="mt-6">{save.isPending ? "正在保存" : "保存备考设置"}</Button></aside></form>;
}

export function ExamSetupPage({ returnTo }: { returnTo?: string }) { const catalog = useExamCatalog(); const profile = useExamProfile(); const destination = resolveReturnDestination(returnTo, "/exam"); if (catalog.isPending || profile.isPending) return <ExamPageShell activeItem="setup"><LoadingRows /></ExamPageShell>; if (catalog.isError || profile.isError) return <ExamPageShell activeItem="setup"><RequestState error={catalog.error ?? profile.error} /></ExamPageShell>; return <ExamPageShell activeItem="setup"><div className="exam-setup"><aside><p className="exam-kicker">备考配置</p><ConfigurationStepRail /></aside><div><DossierHeader index="01" eyebrow="配置工作台" title="设置我的备考"><p className="exam-dossier__meta">先选方向，再确认实际要准备的科目。</p></DossierHeader><div className="mt-10"><SetupForm key={`${profile.data.selected_track}-${profile.data.selected_subjects.join(",")}`} catalog={catalog.data} profile={profile.data} destination={destination} /></div></div></div></ExamPageShell>; }

export function SubjectsCatalogPage() { const catalog = useExamCatalog(); const profile = useExamProfile(); if (catalog.isPending || profile.isPending) return <ExamPageShell activeItem="subjects"><LoadingRows /></ExamPageShell>; if (catalog.isError || profile.isError) return <ExamPageShell activeItem="subjects"><RequestState error={catalog.error ?? profile.error} /></ExamPageShell>; const selected = new Set(profile.data.selected_subjects); let itemIndex = 1; return <ExamPageShell activeItem="subjects"><DossierHeader eyebrow="科目目录" title="全国统考科目目录"><p className="exam-catalogue-intro">选择可加入备考的全国统考科目；目录只呈现当前真实的科目与内容状态。</p></DossierHeader>{categories(catalog.data).map((category) => <section key={category} className="exam-category"><div className="exam-category__label"><h2>{categoryLabel(category)}</h2></div><ul className="exam-index-list">{catalog.data.subjects.filter((subject) => subject.category === category).map((subject) => <SubjectIndexRow key={subject.id} subject={subject} selected={selected.has(subject.id)} index={itemIndex++} />)}</ul></section>)}</ExamPageShell>; }

export function SubjectDetailPage({ subjectId }: { subjectId: string }) { const catalog = useExamCatalog(); const profile = useExamProfile(); const status = useExamSubjectContentStatus(subjectId); if (catalog.isPending || profile.isPending || status.isPending) return <ExamPageShell activeItem="subjects"><LoadingRows /></ExamPageShell>; if (catalog.isError || profile.isError) return <ExamPageShell activeItem="subjects"><RequestState error={catalog.error ?? profile.error} /></ExamPageShell>; const subject = catalog.data.subjects.find((item) => item.id === subjectId); if (!subject) return <ExamPageShell activeItem="subjects"><RequestState error={new Error("not found")} /></ExamPageShell>; if (status.isError && apiState(status.error).kind === "content_unavailable") return <ExamPageShell activeItem="subjects"><ContentUnavailableState subjectName={subject.display_name} selected={profile.data.selected_subjects.includes(subject.id)} /></ExamPageShell>; if (status.isError) return <ExamPageShell activeItem="subjects"><RequestState error={status.error} /></ExamPageShell>; return <ExamPageShell activeItem="subjects"><DossierHeader index="01" eyebrow="内容已开放" title={subject.display_name} dark><p className="exam-dossier__meta">{status.data.modules.map((module) => module.display_name).join(" / ")}</p><div className="exam-dossier__action"><Button asChild><Link to="/exam/cs408">进入 CS408<ArrowRight className="size-4" /></Link></Button></div></DossierHeader></ExamPageShell>; }
