/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgrammingRouteImport } from './routes/programming'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CourseIndexRouteImport } from './routes/course/index'
import { Route as CourseCourseIdRouteImport } from './routes/course/$courseId'
import { Route as CourseSetupRouteImport } from './routes/course/setup'
import { Route as ExamIndexRouteImport } from './routes/exam/index'
import { Route as ExamCs408RouteImport } from './routes/exam/cs408'
import { Route as ExamSetupRouteImport } from './routes/exam/setup'
import { Route as MembershipIndexRouteImport } from './routes/membership/index'
import { Route as MembershipPaymentRouteImport } from './routes/membership/payment'
import { Route as ProgrammingIndexRouteImport } from './routes/programming/index'
import { Route as ProgrammingSplatRouteImport } from './routes/programming/$'
import { Route as ProgrammingPlanRouteImport } from './routes/programming/plan'
import { Route as ProgrammingSetupRouteImport } from './routes/programming/setup'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course/$courseId/index'
import { Route as CourseCourseIdAskRouteImport } from './routes/course/$courseId/ask'
import { Route as CourseCourseIdKnowledgeRouteImport } from './routes/course/$courseId/knowledge'
import { Route as CourseCourseIdMaterialsRouteImport } from './routes/course/$courseId/materials'
import { Route as CourseCourseIdPlanRouteImport } from './routes/course/$courseId/plan'
import { Route as CourseCourseIdPracticeRouteImport } from './routes/course/$courseId/practice'
import { Route as CourseCourseIdRecordsRouteImport } from './routes/course/$courseId/records'
import { Route as CourseCourseIdStateRouteImport } from './routes/course/$courseId/state'
import { Route as CourseCourseIdStudyRouteImport } from './routes/course/$courseId/study'
import { Route as CourseCourseIdWrongRouteImport } from './routes/course/$courseId/wrong'
import { Route as ExamCs408IndexRouteImport } from './routes/exam/cs408/index'
import { Route as ExamCs408AskRouteImport } from './routes/exam/cs408/ask'
import { Route as ExamCs408KnowledgeRouteImport } from './routes/exam/cs408/knowledge'
import { Route as ExamCs408MaterialsRouteImport } from './routes/exam/cs408/materials'
import { Route as ExamCs408PastPapersRouteImport } from './routes/exam/cs408/past-papers'
import { Route as ExamCs408PlanRouteImport } from './routes/exam/cs408/plan'
import { Route as ExamCs408PracticeRouteImport } from './routes/exam/cs408/practice'
import { Route as ExamCs408RecordsRouteImport } from './routes/exam/cs408/records'
import { Route as ExamCs408StateRouteImport } from './routes/exam/cs408/state'
import { Route as ExamCs408WrongRouteImport } from './routes/exam/cs408/wrong'
import { Route as ExamSubjectsIndexRouteImport } from './routes/exam/subjects/index'
import { Route as ExamSubjectsSubjectIdRouteImport } from './routes/exam/subjects/$subjectId'
import { Route as ProgrammingWorkbenchIndexRouteImport } from './routes/programming/workbench/index'
import { Route as ProgrammingWorkbenchExerciseIdRouteImport } from './routes/programming/workbench/$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammingRoute = ProgrammingRouteImport.update({
  id: '/programming',
  path: '/programming',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseRoute,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CourseRoute,
} as any)
const CourseSetupRoute = CourseSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => CourseRoute,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamRoute,
} as any)
const ExamCs408Route = ExamCs408RouteImport.update({
  id: '/cs408',
  path: '/cs408',
  getParentRoute: () => ExamRoute,
} as any)
const ExamSetupRoute = ExamSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ExamRoute,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembershipRoute,
} as any)
const MembershipPaymentRoute = MembershipPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => MembershipRoute,
} as any)
const ProgrammingIndexRoute = ProgrammingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammingRoute,
} as any)
const ProgrammingSplatRoute = ProgrammingSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ProgrammingRoute,
} as any)
const ProgrammingPlanRoute = ProgrammingPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ProgrammingRoute,
} as any)
const ProgrammingSetupRoute = ProgrammingSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ProgrammingRoute,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdAskRoute = CourseCourseIdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdKnowledgeRoute = CourseCourseIdKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdMaterialsRoute = CourseCourseIdMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdPlanRoute = CourseCourseIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdPracticeRoute = CourseCourseIdPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdRecordsRoute = CourseCourseIdRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdStateRoute = CourseCourseIdStateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdStudyRoute = CourseCourseIdStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdWrongRoute = CourseCourseIdWrongRouteImport.update({
  id: '/wrong',
  path: '/wrong',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const ExamCs408IndexRoute = ExamCs408IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408AskRoute = ExamCs408AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408KnowledgeRoute = ExamCs408KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408MaterialsRoute = ExamCs408MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408PastPapersRoute = ExamCs408PastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408PlanRoute = ExamCs408PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408PracticeRoute = ExamCs408PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408RecordsRoute = ExamCs408RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408StateRoute = ExamCs408StateRouteImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamCs408WrongRoute = ExamCs408WrongRouteImport.update({
  id: '/wrong',
  path: '/wrong',
  getParentRoute: () => ExamCs408Route,
} as any)
const ExamSubjectsIndexRoute = ExamSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => ExamRoute,
} as any)
const ExamSubjectsSubjectIdRoute = ExamSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => ExamRoute,
} as any)
const ProgrammingWorkbenchIndexRoute =
  ProgrammingWorkbenchIndexRouteImport.update({
    id: '/workbench/',
    path: '/workbench/',
    getParentRoute: () => ProgrammingRoute,
  } as any)
const ProgrammingWorkbenchExerciseIdRoute =
  ProgrammingWorkbenchExerciseIdRouteImport.update({
    id: '/workbench/$exerciseId',
    path: '/workbench/$exerciseId',
    getParentRoute: () => ProgrammingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/course': typeof CourseRouteWithChildren
  '/exam': typeof ExamRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programming': typeof ProgrammingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/course/setup': typeof CourseSetupRoute
  '/exam/cs408': typeof ExamCs408RouteWithChildren
  '/exam/setup': typeof ExamSetupRoute
  '/membership/payment': typeof MembershipPaymentRoute
  '/programming/$': typeof ProgrammingSplatRoute
  '/programming/plan': typeof ProgrammingPlanRoute
  '/programming/setup': typeof ProgrammingSetupRoute
  '/course/': typeof CourseIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/programming/': typeof ProgrammingIndexRoute
  '/course/$courseId/ask': typeof CourseCourseIdAskRoute
  '/course/$courseId/knowledge': typeof CourseCourseIdKnowledgeRoute
  '/course/$courseId/materials': typeof CourseCourseIdMaterialsRoute
  '/course/$courseId/plan': typeof CourseCourseIdPlanRoute
  '/course/$courseId/practice': typeof CourseCourseIdPracticeRoute
  '/course/$courseId/records': typeof CourseCourseIdRecordsRoute
  '/course/$courseId/state': typeof CourseCourseIdStateRoute
  '/course/$courseId/study': typeof CourseCourseIdStudyRoute
  '/course/$courseId/wrong': typeof CourseCourseIdWrongRoute
  '/exam/cs408/ask': typeof ExamCs408AskRoute
  '/exam/cs408/knowledge': typeof ExamCs408KnowledgeRoute
  '/exam/cs408/materials': typeof ExamCs408MaterialsRoute
  '/exam/cs408/past-papers': typeof ExamCs408PastPapersRoute
  '/exam/cs408/plan': typeof ExamCs408PlanRoute
  '/exam/cs408/practice': typeof ExamCs408PracticeRoute
  '/exam/cs408/records': typeof ExamCs408RecordsRoute
  '/exam/cs408/state': typeof ExamCs408StateRoute
  '/exam/cs408/wrong': typeof ExamCs408WrongRoute
  '/exam/subjects/$subjectId': typeof ExamSubjectsSubjectIdRoute
  '/programming/workbench/$exerciseId': typeof ProgrammingWorkbenchExerciseIdRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/exam/cs408/': typeof ExamCs408IndexRoute
  '/exam/subjects/': typeof ExamSubjectsIndexRoute
  '/programming/workbench/': typeof ProgrammingWorkbenchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/course/setup': typeof CourseSetupRoute
  '/exam/setup': typeof ExamSetupRoute
  '/membership/payment': typeof MembershipPaymentRoute
  '/programming/$': typeof ProgrammingSplatRoute
  '/programming/plan': typeof ProgrammingPlanRoute
  '/programming/setup': typeof ProgrammingSetupRoute
  '/course': typeof CourseIndexRoute
  '/exam': typeof ExamIndexRoute
  '/membership': typeof MembershipIndexRoute
  '/programming': typeof ProgrammingIndexRoute
  '/course/$courseId/ask': typeof CourseCourseIdAskRoute
  '/course/$courseId/knowledge': typeof CourseCourseIdKnowledgeRoute
  '/course/$courseId/materials': typeof CourseCourseIdMaterialsRoute
  '/course/$courseId/plan': typeof CourseCourseIdPlanRoute
  '/course/$courseId/practice': typeof CourseCourseIdPracticeRoute
  '/course/$courseId/records': typeof CourseCourseIdRecordsRoute
  '/course/$courseId/state': typeof CourseCourseIdStateRoute
  '/course/$courseId/study': typeof CourseCourseIdStudyRoute
  '/course/$courseId/wrong': typeof CourseCourseIdWrongRoute
  '/exam/cs408/ask': typeof ExamCs408AskRoute
  '/exam/cs408/knowledge': typeof ExamCs408KnowledgeRoute
  '/exam/cs408/materials': typeof ExamCs408MaterialsRoute
  '/exam/cs408/past-papers': typeof ExamCs408PastPapersRoute
  '/exam/cs408/plan': typeof ExamCs408PlanRoute
  '/exam/cs408/practice': typeof ExamCs408PracticeRoute
  '/exam/cs408/records': typeof ExamCs408RecordsRoute
  '/exam/cs408/state': typeof ExamCs408StateRoute
  '/exam/cs408/wrong': typeof ExamCs408WrongRoute
  '/exam/subjects/$subjectId': typeof ExamSubjectsSubjectIdRoute
  '/programming/workbench/$exerciseId': typeof ProgrammingWorkbenchExerciseIdRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/exam/cs408': typeof ExamCs408IndexRoute
  '/exam/subjects': typeof ExamSubjectsIndexRoute
  '/programming/workbench': typeof ProgrammingWorkbenchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/course': typeof CourseRouteWithChildren
  '/exam': typeof ExamRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programming': typeof ProgrammingRouteWithChildren
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/course/setup': typeof CourseSetupRoute
  '/exam/cs408': typeof ExamCs408RouteWithChildren
  '/exam/setup': typeof ExamSetupRoute
  '/membership/payment': typeof MembershipPaymentRoute
  '/programming/$': typeof ProgrammingSplatRoute
  '/programming/plan': typeof ProgrammingPlanRoute
  '/programming/setup': typeof ProgrammingSetupRoute
  '/course/': typeof CourseIndexRoute
  '/exam/': typeof ExamIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/programming/': typeof ProgrammingIndexRoute
  '/course/$courseId/ask': typeof CourseCourseIdAskRoute
  '/course/$courseId/knowledge': typeof CourseCourseIdKnowledgeRoute
  '/course/$courseId/materials': typeof CourseCourseIdMaterialsRoute
  '/course/$courseId/plan': typeof CourseCourseIdPlanRoute
  '/course/$courseId/practice': typeof CourseCourseIdPracticeRoute
  '/course/$courseId/records': typeof CourseCourseIdRecordsRoute
  '/course/$courseId/state': typeof CourseCourseIdStateRoute
  '/course/$courseId/study': typeof CourseCourseIdStudyRoute
  '/course/$courseId/wrong': typeof CourseCourseIdWrongRoute
  '/exam/cs408/ask': typeof ExamCs408AskRoute
  '/exam/cs408/knowledge': typeof ExamCs408KnowledgeRoute
  '/exam/cs408/materials': typeof ExamCs408MaterialsRoute
  '/exam/cs408/past-papers': typeof ExamCs408PastPapersRoute
  '/exam/cs408/plan': typeof ExamCs408PlanRoute
  '/exam/cs408/practice': typeof ExamCs408PracticeRoute
  '/exam/cs408/records': typeof ExamCs408RecordsRoute
  '/exam/cs408/state': typeof ExamCs408StateRoute
  '/exam/cs408/wrong': typeof ExamCs408WrongRoute
  '/exam/subjects/$subjectId': typeof ExamSubjectsSubjectIdRoute
  '/programming/workbench/$exerciseId': typeof ProgrammingWorkbenchExerciseIdRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/exam/cs408/': typeof ExamCs408IndexRoute
  '/exam/subjects/': typeof ExamSubjectsIndexRoute
  '/programming/workbench/': typeof ProgrammingWorkbenchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/course'
    | '/exam'
    | '/login'
    | '/membership'
    | '/privacy'
    | '/profile'
    | '/programming'
    | '/register'
    | '/reports'
    | '/review'
    | '/terms'
    | '/course/$courseId'
    | '/course/setup'
    | '/exam/cs408'
    | '/exam/setup'
    | '/membership/payment'
    | '/programming/$'
    | '/programming/plan'
    | '/programming/setup'
    | '/course/'
    | '/exam/'
    | '/membership/'
    | '/programming/'
    | '/course/$courseId/ask'
    | '/course/$courseId/knowledge'
    | '/course/$courseId/materials'
    | '/course/$courseId/plan'
    | '/course/$courseId/practice'
    | '/course/$courseId/records'
    | '/course/$courseId/state'
    | '/course/$courseId/study'
    | '/course/$courseId/wrong'
    | '/exam/cs408/ask'
    | '/exam/cs408/knowledge'
    | '/exam/cs408/materials'
    | '/exam/cs408/past-papers'
    | '/exam/cs408/plan'
    | '/exam/cs408/practice'
    | '/exam/cs408/records'
    | '/exam/cs408/state'
    | '/exam/cs408/wrong'
    | '/exam/subjects/$subjectId'
    | '/programming/workbench/$exerciseId'
    | '/course/$courseId/'
    | '/exam/cs408/'
    | '/exam/subjects/'
    | '/programming/workbench/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/reports'
    | '/review'
    | '/terms'
    | '/course/setup'
    | '/exam/setup'
    | '/membership/payment'
    | '/programming/$'
    | '/programming/plan'
    | '/programming/setup'
    | '/course'
    | '/exam'
    | '/membership'
    | '/programming'
    | '/course/$courseId/ask'
    | '/course/$courseId/knowledge'
    | '/course/$courseId/materials'
    | '/course/$courseId/plan'
    | '/course/$courseId/practice'
    | '/course/$courseId/records'
    | '/course/$courseId/state'
    | '/course/$courseId/study'
    | '/course/$courseId/wrong'
    | '/exam/cs408/ask'
    | '/exam/cs408/knowledge'
    | '/exam/cs408/materials'
    | '/exam/cs408/past-papers'
    | '/exam/cs408/plan'
    | '/exam/cs408/practice'
    | '/exam/cs408/records'
    | '/exam/cs408/state'
    | '/exam/cs408/wrong'
    | '/exam/subjects/$subjectId'
    | '/programming/workbench/$exerciseId'
    | '/course/$courseId'
    | '/exam/cs408'
    | '/exam/subjects'
    | '/programming/workbench'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/course'
    | '/exam'
    | '/login'
    | '/membership'
    | '/privacy'
    | '/profile'
    | '/programming'
    | '/register'
    | '/reports'
    | '/review'
    | '/terms'
    | '/course/$courseId'
    | '/course/setup'
    | '/exam/cs408'
    | '/exam/setup'
    | '/membership/payment'
    | '/programming/$'
    | '/programming/plan'
    | '/programming/setup'
    | '/course/'
    | '/exam/'
    | '/membership/'
    | '/programming/'
    | '/course/$courseId/ask'
    | '/course/$courseId/knowledge'
    | '/course/$courseId/materials'
    | '/course/$courseId/plan'
    | '/course/$courseId/practice'
    | '/course/$courseId/records'
    | '/course/$courseId/state'
    | '/course/$courseId/study'
    | '/course/$courseId/wrong'
    | '/exam/cs408/ask'
    | '/exam/cs408/knowledge'
    | '/exam/cs408/materials'
    | '/exam/cs408/past-papers'
    | '/exam/cs408/plan'
    | '/exam/cs408/practice'
    | '/exam/cs408/records'
    | '/exam/cs408/state'
    | '/exam/cs408/wrong'
    | '/exam/subjects/$subjectId'
    | '/programming/workbench/$exerciseId'
    | '/course/$courseId/'
    | '/exam/cs408/'
    | '/exam/subjects/'
    | '/programming/workbench/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CourseRoute: typeof CourseRouteWithChildren
  ExamRoute: typeof ExamRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgrammingRoute: typeof ProgrammingRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programming': {
      id: '/programming'
      path: '/programming'
      fullPath: '/programming'
      preLoaderRoute: typeof ProgrammingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof CourseRoute
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof CourseRoute
    }
    '/course/setup': {
      id: '/course/setup'
      path: '/setup'
      fullPath: '/course/setup'
      preLoaderRoute: typeof CourseSetupRouteImport
      parentRoute: typeof CourseRoute
    }
    '/exam/': {
      id: '/exam/'
      path: '/'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/cs408': {
      id: '/exam/cs408'
      path: '/cs408'
      fullPath: '/exam/cs408'
      preLoaderRoute: typeof ExamCs408RouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/setup': {
      id: '/exam/setup'
      path: '/setup'
      fullPath: '/exam/setup'
      preLoaderRoute: typeof ExamSetupRouteImport
      parentRoute: typeof ExamRoute
    }
    '/membership/': {
      id: '/membership/'
      path: '/'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/membership/payment': {
      id: '/membership/payment'
      path: '/payment'
      fullPath: '/membership/payment'
      preLoaderRoute: typeof MembershipPaymentRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/programming/': {
      id: '/programming/'
      path: '/'
      fullPath: '/programming/'
      preLoaderRoute: typeof ProgrammingIndexRouteImport
      parentRoute: typeof ProgrammingRoute
    }
    '/programming/$': {
      id: '/programming/$'
      path: '/$'
      fullPath: '/programming/$'
      preLoaderRoute: typeof ProgrammingSplatRouteImport
      parentRoute: typeof ProgrammingRoute
    }
    '/programming/plan': {
      id: '/programming/plan'
      path: '/plan'
      fullPath: '/programming/plan'
      preLoaderRoute: typeof ProgrammingPlanRouteImport
      parentRoute: typeof ProgrammingRoute
    }
    '/programming/setup': {
      id: '/programming/setup'
      path: '/setup'
      fullPath: '/programming/setup'
      preLoaderRoute: typeof ProgrammingSetupRouteImport
      parentRoute: typeof ProgrammingRoute
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/ask': {
      id: '/course/$courseId/ask'
      path: '/ask'
      fullPath: '/course/$courseId/ask'
      preLoaderRoute: typeof CourseCourseIdAskRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/knowledge': {
      id: '/course/$courseId/knowledge'
      path: '/knowledge'
      fullPath: '/course/$courseId/knowledge'
      preLoaderRoute: typeof CourseCourseIdKnowledgeRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/materials': {
      id: '/course/$courseId/materials'
      path: '/materials'
      fullPath: '/course/$courseId/materials'
      preLoaderRoute: typeof CourseCourseIdMaterialsRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/plan': {
      id: '/course/$courseId/plan'
      path: '/plan'
      fullPath: '/course/$courseId/plan'
      preLoaderRoute: typeof CourseCourseIdPlanRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/practice': {
      id: '/course/$courseId/practice'
      path: '/practice'
      fullPath: '/course/$courseId/practice'
      preLoaderRoute: typeof CourseCourseIdPracticeRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/records': {
      id: '/course/$courseId/records'
      path: '/records'
      fullPath: '/course/$courseId/records'
      preLoaderRoute: typeof CourseCourseIdRecordsRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/state': {
      id: '/course/$courseId/state'
      path: '/state'
      fullPath: '/course/$courseId/state'
      preLoaderRoute: typeof CourseCourseIdStateRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/study': {
      id: '/course/$courseId/study'
      path: '/study'
      fullPath: '/course/$courseId/study'
      preLoaderRoute: typeof CourseCourseIdStudyRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/wrong': {
      id: '/course/$courseId/wrong'
      path: '/wrong'
      fullPath: '/course/$courseId/wrong'
      preLoaderRoute: typeof CourseCourseIdWrongRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/exam/cs408/': {
      id: '/exam/cs408/'
      path: '/'
      fullPath: '/exam/cs408/'
      preLoaderRoute: typeof ExamCs408IndexRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/ask': {
      id: '/exam/cs408/ask'
      path: '/ask'
      fullPath: '/exam/cs408/ask'
      preLoaderRoute: typeof ExamCs408AskRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/knowledge': {
      id: '/exam/cs408/knowledge'
      path: '/knowledge'
      fullPath: '/exam/cs408/knowledge'
      preLoaderRoute: typeof ExamCs408KnowledgeRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/materials': {
      id: '/exam/cs408/materials'
      path: '/materials'
      fullPath: '/exam/cs408/materials'
      preLoaderRoute: typeof ExamCs408MaterialsRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/past-papers': {
      id: '/exam/cs408/past-papers'
      path: '/past-papers'
      fullPath: '/exam/cs408/past-papers'
      preLoaderRoute: typeof ExamCs408PastPapersRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/plan': {
      id: '/exam/cs408/plan'
      path: '/plan'
      fullPath: '/exam/cs408/plan'
      preLoaderRoute: typeof ExamCs408PlanRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/practice': {
      id: '/exam/cs408/practice'
      path: '/practice'
      fullPath: '/exam/cs408/practice'
      preLoaderRoute: typeof ExamCs408PracticeRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/records': {
      id: '/exam/cs408/records'
      path: '/records'
      fullPath: '/exam/cs408/records'
      preLoaderRoute: typeof ExamCs408RecordsRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/state': {
      id: '/exam/cs408/state'
      path: '/state'
      fullPath: '/exam/cs408/state'
      preLoaderRoute: typeof ExamCs408StateRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/cs408/wrong': {
      id: '/exam/cs408/wrong'
      path: '/wrong'
      fullPath: '/exam/cs408/wrong'
      preLoaderRoute: typeof ExamCs408WrongRouteImport
      parentRoute: typeof ExamCs408Route
    }
    '/exam/subjects/': {
      id: '/exam/subjects/'
      path: '/subjects'
      fullPath: '/exam/subjects/'
      preLoaderRoute: typeof ExamSubjectsIndexRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/subjects/$subjectId': {
      id: '/exam/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/exam/subjects/$subjectId'
      preLoaderRoute: typeof ExamSubjectsSubjectIdRouteImport
      parentRoute: typeof ExamRoute
    }
    '/programming/workbench/': {
      id: '/programming/workbench/'
      path: '/workbench'
      fullPath: '/programming/workbench/'
      preLoaderRoute: typeof ProgrammingWorkbenchIndexRouteImport
      parentRoute: typeof ProgrammingRoute
    }
    '/programming/workbench/$exerciseId': {
      id: '/programming/workbench/$exerciseId'
      path: '/workbench/$exerciseId'
      fullPath: '/programming/workbench/$exerciseId'
      preLoaderRoute: typeof ProgrammingWorkbenchExerciseIdRouteImport
      parentRoute: typeof ProgrammingRoute
    }
  }
}

interface CourseCourseIdRouteChildren {
  CourseCourseIdAskRoute: typeof CourseCourseIdAskRoute
  CourseCourseIdKnowledgeRoute: typeof CourseCourseIdKnowledgeRoute
  CourseCourseIdMaterialsRoute: typeof CourseCourseIdMaterialsRoute
  CourseCourseIdPlanRoute: typeof CourseCourseIdPlanRoute
  CourseCourseIdPracticeRoute: typeof CourseCourseIdPracticeRoute
  CourseCourseIdRecordsRoute: typeof CourseCourseIdRecordsRoute
  CourseCourseIdStateRoute: typeof CourseCourseIdStateRoute
  CourseCourseIdStudyRoute: typeof CourseCourseIdStudyRoute
  CourseCourseIdWrongRoute: typeof CourseCourseIdWrongRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
}

const CourseCourseIdRouteChildren: CourseCourseIdRouteChildren = {
  CourseCourseIdAskRoute: CourseCourseIdAskRoute,
  CourseCourseIdKnowledgeRoute: CourseCourseIdKnowledgeRoute,
  CourseCourseIdMaterialsRoute: CourseCourseIdMaterialsRoute,
  CourseCourseIdPlanRoute: CourseCourseIdPlanRoute,
  CourseCourseIdPracticeRoute: CourseCourseIdPracticeRoute,
  CourseCourseIdRecordsRoute: CourseCourseIdRecordsRoute,
  CourseCourseIdStateRoute: CourseCourseIdStateRoute,
  CourseCourseIdStudyRoute: CourseCourseIdStudyRoute,
  CourseCourseIdWrongRoute: CourseCourseIdWrongRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
}

const CourseCourseIdRouteWithChildren = CourseCourseIdRoute._addFileChildren(
  CourseCourseIdRouteChildren,
)

interface CourseRouteChildren {
  CourseCourseIdRoute: typeof CourseCourseIdRouteWithChildren
  CourseSetupRoute: typeof CourseSetupRoute
  CourseIndexRoute: typeof CourseIndexRoute
}

const CourseRouteChildren: CourseRouteChildren = {
  CourseCourseIdRoute: CourseCourseIdRouteWithChildren,
  CourseSetupRoute: CourseSetupRoute,
  CourseIndexRoute: CourseIndexRoute,
}

const CourseRouteWithChildren =
  CourseRoute._addFileChildren(CourseRouteChildren)

interface ExamCs408RouteChildren {
  ExamCs408AskRoute: typeof ExamCs408AskRoute
  ExamCs408KnowledgeRoute: typeof ExamCs408KnowledgeRoute
  ExamCs408MaterialsRoute: typeof ExamCs408MaterialsRoute
  ExamCs408PastPapersRoute: typeof ExamCs408PastPapersRoute
  ExamCs408PlanRoute: typeof ExamCs408PlanRoute
  ExamCs408PracticeRoute: typeof ExamCs408PracticeRoute
  ExamCs408RecordsRoute: typeof ExamCs408RecordsRoute
  ExamCs408StateRoute: typeof ExamCs408StateRoute
  ExamCs408WrongRoute: typeof ExamCs408WrongRoute
  ExamCs408IndexRoute: typeof ExamCs408IndexRoute
}

const ExamCs408RouteChildren: ExamCs408RouteChildren = {
  ExamCs408AskRoute: ExamCs408AskRoute,
  ExamCs408KnowledgeRoute: ExamCs408KnowledgeRoute,
  ExamCs408MaterialsRoute: ExamCs408MaterialsRoute,
  ExamCs408PastPapersRoute: ExamCs408PastPapersRoute,
  ExamCs408PlanRoute: ExamCs408PlanRoute,
  ExamCs408PracticeRoute: ExamCs408PracticeRoute,
  ExamCs408RecordsRoute: ExamCs408RecordsRoute,
  ExamCs408StateRoute: ExamCs408StateRoute,
  ExamCs408WrongRoute: ExamCs408WrongRoute,
  ExamCs408IndexRoute: ExamCs408IndexRoute,
}

const ExamCs408RouteWithChildren = ExamCs408Route._addFileChildren(
  ExamCs408RouteChildren,
)

interface ExamRouteChildren {
  ExamCs408Route: typeof ExamCs408RouteWithChildren
  ExamSetupRoute: typeof ExamSetupRoute
  ExamIndexRoute: typeof ExamIndexRoute
  ExamSubjectsSubjectIdRoute: typeof ExamSubjectsSubjectIdRoute
  ExamSubjectsIndexRoute: typeof ExamSubjectsIndexRoute
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamCs408Route: ExamCs408RouteWithChildren,
  ExamSetupRoute: ExamSetupRoute,
  ExamIndexRoute: ExamIndexRoute,
  ExamSubjectsSubjectIdRoute: ExamSubjectsSubjectIdRoute,
  ExamSubjectsIndexRoute: ExamSubjectsIndexRoute,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

interface MembershipRouteChildren {
  MembershipPaymentRoute: typeof MembershipPaymentRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
}

const MembershipRouteChildren: MembershipRouteChildren = {
  MembershipPaymentRoute: MembershipPaymentRoute,
  MembershipIndexRoute: MembershipIndexRoute,
}

const MembershipRouteWithChildren = MembershipRoute._addFileChildren(
  MembershipRouteChildren,
)

interface ProgrammingRouteChildren {
  ProgrammingSplatRoute: typeof ProgrammingSplatRoute
  ProgrammingPlanRoute: typeof ProgrammingPlanRoute
  ProgrammingSetupRoute: typeof ProgrammingSetupRoute
  ProgrammingIndexRoute: typeof ProgrammingIndexRoute
  ProgrammingWorkbenchExerciseIdRoute: typeof ProgrammingWorkbenchExerciseIdRoute
  ProgrammingWorkbenchIndexRoute: typeof ProgrammingWorkbenchIndexRoute
}

const ProgrammingRouteChildren: ProgrammingRouteChildren = {
  ProgrammingSplatRoute: ProgrammingSplatRoute,
  ProgrammingPlanRoute: ProgrammingPlanRoute,
  ProgrammingSetupRoute: ProgrammingSetupRoute,
  ProgrammingIndexRoute: ProgrammingIndexRoute,
  ProgrammingWorkbenchExerciseIdRoute: ProgrammingWorkbenchExerciseIdRoute,
  ProgrammingWorkbenchIndexRoute: ProgrammingWorkbenchIndexRoute,
}

const ProgrammingRouteWithChildren = ProgrammingRoute._addFileChildren(
  ProgrammingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CourseRoute: CourseRouteWithChildren,
  ExamRoute: ExamRouteWithChildren,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgrammingRoute: ProgrammingRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
