import { chromium } from "playwright";
import path from "node:path";
import { fileURLToPath } from "node:url";
const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const AUTH = path.join(PROJECT_ROOT, ".playwright", ".auth", "stage4-materials-relogin-production.json");
const BASE = "https://101.32.190.42";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ storageState: AUTH });
const r = await ctx.request.post(`${BASE}/api/me`, { data: { username: "奶12" } });
const j = await r.json().catch(() => ({}));
console.log("tracks:", JSON.stringify((j?.user?.tracks||[]).map(t => `${t.track_type}:${t.package_type}:${t.is_active}`)));
console.log("service_plans:", JSON.stringify(Object.fromEntries(Object.entries(j?.user?.service_plans||{}).map(([k,v]) => [k, v.plan]))));
await browser.close();
