"""Canonical LearningEvent envelope: build + validate.

The frozen target envelope (event_id, user_id, event_type, service_namespace, context,
occurred_at, source, payload, schema_version) maps onto the EXISTING ``learning_events``
columns — they already express every one of those fields, so STEP 7F adds no column and
no second record table:

    event_id             → event_id
    user_id              → user_id (+ source_user_ref for legacy traceability)
    event_type           → event_type
    service_namespace    → service_key        (canonical app-layer name; frozen mapping)
    context              → course_id / subject_key / question_id / knowledge_point_ref_json
                           (``knowledge_point_ref_json`` is the domain-context JSON and
                            also carries ``exam_module_id`` for exam_prep facts; it is
                            not part of event identity)
    occurred_at          → occurred_at
    source               → source_type / source_attempt_id / source_item_key /
                           source_item_index
    payload              → item_snapshot_json (+ item_content_hash)
    schema_version       → event_schema_version

Identity is generated by the FROZEN ``data_plane.identity`` functions — no second UUID
namespace is introduced, so live and backfill events for the same fact always agree.
"""
from __future__ import annotations

import logging
import time

from core.learning_context import (
    VALID_SERVICE_NAMESPACES,
    resolve_event_subject_key,
)
from data_plane import identity

from . import native_concept
from .taxonomy import EVENT_SCHEMA_VERSION, ITEM_LEVEL, spec_for

logger = logging.getLogger("learning.records")

VALID_COMPLETENESS = ("FULL", "PARTIAL")


class EventValidationError(ValueError):
    """A payload that must not enter the canonical stream."""


# Absent keys are OMITTED rather than stored as null, so an event built before a field
# existed and one built after it stays blank compare equal. The key set is owned by
# ``native_concept`` (ACCEL_SPRINT_S5) so the writer here and the reader in the KT dataset
# export cannot drift apart.
_DOMAIN_CONTEXT_KEYS = native_concept.NATIVE_CONCEPT_KEYS


def domain_context_json(context: dict) -> dict:
    """The domain-context JSON stored on the event row.

    Additive and NOT identity-bearing (``event_id`` / ``idempotency_key`` depend only on
    the source triple), so carrying ``exam_module_id`` here needs no migration.
    """
    return native_concept.reference_from_context(context)


def build_event(*, event_type: str, user_id: int, service_namespace: str,
                occurred_at: float, source_type: str, source_id,
                source_item_key, payload: dict, context: dict | None = None,
                source_user_ref: str | None = None, source_item_index: int = 0,
                granularity: str | None = None, snapshot_capture_mode: str,
                snapshot_completeness: str = "PARTIAL",
                snapshot_missing_fields: list | None = None,
                source_payload_version: int = 1) -> dict:
    """Build a canonical event row dict. Raises EventValidationError when invalid."""
    spec = spec_for(event_type)
    if spec is None:
        raise EventValidationError(f"unregistered event_type {event_type!r}")

    context = context or {}
    source_item_key = str(source_item_key)
    event = {
        "event_id": identity.event_id(source_type, str(source_id), source_item_key),
        "event_schema_version": EVENT_SCHEMA_VERSION,
        "event_type": event_type,
        "event_granularity": granularity or (spec.granularity if spec else ITEM_LEVEL),
        "source_type": source_type,
        "source_attempt_id": str(source_id),
        "source_item_key": source_item_key,
        "source_item_index": source_item_index,
        "user_id": user_id,
        "source_user_ref": source_user_ref,
        "service_key": service_namespace,
        "course_id": context.get("course_id"),
        "subject_key": resolve_event_subject_key(context),
        "question_id": context.get("question_id"),
        "knowledge_point_ref_json": identity.canonical_json(
            domain_context_json(context)),
        "item_snapshot_json": identity.canonical_json(payload),
        "item_content_hash": identity.item_content_hash(payload),
        "answer": payload.get("answer"),
        "correct": payload.get("correct"),
        "score": payload.get("score"),
        "response_time_ms": payload.get("response_time_ms"),
        "attempt_no": payload.get("attempt_no"),
        # ACCEL_SPRINT_S5 telemetry provenance. A duration is only usable together with
        # the boundaries it was measured between, so both fields follow it onto the row.
        "response_time_source": payload.get("response_time_source"),
        "attempt_index": payload.get("attempt_index"),
        "occurred_at": float(occurred_at),
        "ingested_at": time.time(),
        "source_payload_version": source_payload_version,
        "idempotency_key": identity.idempotency_key(source_type, str(source_id),
                                                    source_item_key),
        "snapshot_capture_mode": snapshot_capture_mode,
        "snapshot_completeness": snapshot_completeness,
        "snapshot_missing_fields_json": identity.canonical_json(
            snapshot_missing_fields or []),
    }
    assert_payload_is_safe(payload)
    errors = validate_event(event)
    if errors:
        raise EventValidationError("; ".join(errors))
    return event


# Fields that live in their own ``learning_events`` COLUMN. A producer satisfies such a
# requirement by carrying the value in the row (``correct`` is tri-state, so "present and
# null" is a real, honest answer — not a missing field).
_COLUMN_BACKED = frozenset({"answer", "correct", "score", "response_time_ms", "attempt_no"})


def validate_event(event: dict) -> list[str]:
    """Canonical validation. Returns a list of errors (empty = valid).

    Invalid events are REJECTED, never silently repaired (§32).
    """
    errors: list[str] = []
    spec = spec_for(event.get("event_type", ""))
    if spec is None:
        return [f"unregistered event_type {event.get('event_type')!r}"]
    if spec.status != "ACTIVE":
        errors.append(f"event_type {spec.event_type} is {spec.status}, not emittable")

    if not event.get("event_id"):
        errors.append("event_id missing")
    if event.get("user_id") is None:
        errors.append("user_id missing")
    namespace = event.get("service_key")
    if namespace not in VALID_SERVICE_NAMESPACES:
        errors.append(f"invalid service_namespace {namespace!r}")
    elif spec.namespaces and namespace not in spec.namespaces:
        errors.append(f"event_type {spec.event_type} is not valid for {namespace}")

    version = event.get("event_schema_version")
    if version != EVENT_SCHEMA_VERSION:
        errors.append(f"unsupported event_schema_version {version!r}")

    occurred = event.get("occurred_at")
    if not isinstance(occurred, (int, float)) or isinstance(occurred, bool):
        errors.append("occurred_at must be a UTC epoch number")
    elif occurred <= 0:
        errors.append("occurred_at must be positive")

    if not event.get("source_type"):
        errors.append("source identity (source_type) missing")
    if event.get("source_attempt_id") in (None, ""):
        errors.append("source identity (source_attempt_id) missing")
    if event.get("source_item_key") in (None, ""):
        errors.append("source identity (source_item_key) missing")
    if not event.get("idempotency_key"):
        errors.append("idempotency_key missing")

    completeness = event.get("snapshot_completeness")
    if completeness not in VALID_COMPLETENESS:
        errors.append(f"invalid snapshot_completeness {completeness!r}")

    payload = _payload_of(event)
    for field in spec.required_payload:
        if field in _COLUMN_BACKED:
            if field not in event:
                errors.append(f"{spec.event_type} requires the {field!r} column")
        elif field not in payload:
            errors.append(f"{spec.event_type} requires payload field {field!r}")

    # numeric fields must not arrive as bools, and correct stays tri-state
    for field in ("score",):
        value = event.get(field)
        if value is not None and (isinstance(value, bool) or not isinstance(value, (int, float))):
            errors.append(f"{field} must be numeric or null")
    correct = event.get("correct")
    if correct is not None and not isinstance(correct, bool):
        errors.append("correct must be true/false/null")
    return errors


def _payload_of(event: dict) -> dict:
    import json
    try:
        data = json.loads(event.get("item_snapshot_json") or "{}")
        return data if isinstance(data, dict) else {}
    except (TypeError, ValueError):
        return {}


# ---- privacy guard (§34) ----

FORBIDDEN_PAYLOAD_KEYS = (
    "code", "source_code", "answer_text", "full_answer", "prompt", "raw_prompt",
    "response", "raw_response", "content", "material_body", "api_key", "secret",
    "password", "token",
)


def assert_payload_is_safe(payload: dict) -> None:
    """Reject payloads that would copy bulk user content into the event stream.

    Identifiers, references and small factual metrics are fine; verbatim answers,
    source code, prompts, responses and material bodies belong to their domain tables.
    """
    lowered = {str(k).lower() for k in (payload or {})}
    offenders = sorted(lowered & set(FORBIDDEN_PAYLOAD_KEYS))
    if offenders:
        raise EventValidationError(
            f"payload contains fields that must stay in the domain tables: {offenders}")
